<?php
	require_once('../../private/initialize.php');
	$page_title = 'Planeta Sano';
	include(SHARED_PATH . '/header.php');
?>
<main class="container">
	<div class="row p-4 justify-content-arround">
		<h2>Contaminación ambiental</h2>
			<p class="justificado">Te has preguntado como afectamos el planeta deja platicarte sobre algunas consecuencias que tiene el no cuidar el medio ambiente es el agotar los recursos naturales hacer un consumo excesivo de lo que es el agua dulce, la tierra cultivable, madera y combustibles fósiles nos lleva a lo que es la deforestación, la perdida de biodiversidad y la escasez de recursos. Usar de forma intensiva la tierra para la agricultura, la urbanización y otras actividades humanas que afecten el suelo esto nos trae como consecuencia la desertificación, la erosión del suelo y la pérdida de hábitats naturales.<br>
			Las actividades que llevamos afectan mucho al planeta, actividades como la industria, el transporte, y la agricultura intensiva traen consecuencias como emisiones de gases de efecto invernadero, contaminantes atmosféricos, productos químicos agrícolas y residuos sólidos. Las emisiones de gases de efecto invernadero son provocadas cuando quemamos combustibles fósiles para la energía y el transporte que generan como consecuencias globales el aumento de las temperaturas, el derretimiento de los casquetes polares, el aumento del nivel del mar y la acidificación de los océanos.<br>
			El expandir áreas urbanas la conversión de hábitats naturales en tierras de cultivo y la sobreexplotación de recursos naturales provocan la perdida de biodiversidad trayendo como consecuencia en los ecosistemas esto debido a que varias plantas y animales dependen unos de otros para sobrevivir. El no ser consciente del daño que le causamos al planeta provoca consecuencias como la escasez de recursos, la degradación del medio ambiente y el cambio climático que nos traen como amenaza la seguridad alimentaria, el acceso al agua potable y el bienestar de las poblaciones vulnerables. Seamos conscientes de lo que estamos provocando, el ser humano contamina de diferentes formas como la <a href="<?php echo url_for('paginas/contaminacionSuelo.php');?>">contaminacion del suelo</a>, la <a href="<?php echo url_for('paginas/contaminacionAire.php');?>">contaminacion del aire</a>, la <a href="<?php echo url_for('paginas/contaminacionAgua.php');?>">contaminacion del agua</a> y la <a href="<?php echo url_for('paginas/contaminacionTermica.php');?>">contaminacion termica</a> todas son diferentes pero impactan de la misma forma, has conciencia y reflexiona sobre el daño que le causas al planeta.</p>	
			<iframe width="560" height="315" src="https://www.youtube.com/embed/21abiu5ftMQ?si=V9hWpB5_NkE8dYO7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
	</div>
</main>